### ISSUE TITLE
Not good enough from example point of view 

### ISSUE THREAD

**Issue by chaitanya073** [jepiqueau/vue-datastoragesqlite-app#1]
**There are few things which are confusing me**

1. You didn't imported capacitor-data-storage-sqlite once in your project and magically it is working I read every single file and I can't figure out how you did that.PS : I am not taking about wrapper.vue component.
2. Other thing is that I did exactly same what you did but code wasn't working the only thing that was different was I was using vue 2 and without ionic 
3. one more thing is that the openStore function the doc doesn't say anything about it and thing is that does the function creates the database for us if it doesn't exits or there is other function do it. 
4. Moreover do we have to install sqlite or plugin itself install for us.

**Thanks for making plugin unfortunately I can't figure out these things**
**I know this is not write place but I didn't want to span the main plugin repo**
PS : I am using vue 2 with JS , vuetify as ui library

**Comment by jepiqueau** [comment]
@Codereapers Thanks for trying to use the plugin and sorry if there are confusion. I didn't updated this app from quite so long but i have updated `https://github.com/jepiqueau/vue-capacitor-data-storage-sqlite` and `https://github.com/jepiqueau/vue-data-storage-sqlite-app-starter` So i have to update this one too.

- you did not see the import of `capacitor-data-storage-sqlite` as in those apps i am using the hook `vue-data-storage-sqlite-hook` which is based on `capacitor-data-storage-sqlite` and if you look in the package.json file you will see that i have installed both. The reason i can do that is i work with Vue3 which have a composition API. So the hook is a composable based on `capacitor-data-storage-sqlite`.
- so in fact i should develop a app based on pure js and vue2 in that case i will use directly the `capacitor-data-storage-sqlite` plugin 
- the openStore function is described in the doc `https://github.com/jepiqueau/capacitor-data-storage-sqlite/blob/master/docs/API.md`and in fact open a store(database) with the specific table. if not options are given the database is named `storage` and the table `storage_table` . the database is created if it doesn't exist and/or is  opened.

- Which platform are you using? Native nothing to do, Web install `localforage`, Electron follow the instructions on the README.
Hope this will be helpful, do not hesitate to come back.

**Comment by jepiqueau** [comment]
@Codereapers i build up a quick app in Vue.js 2 with the latest releases `https://github.com/jepiqueau/vue2-storage-sqlite-app` Hope this will help you to start your own development

**Comment by chaitanya073** [comment]
Man you are amazing I didn't really though that you would answer but I am surprised you are a real **GOAT** man thanks for [https://github.com/jepiqueau/vue2-storage-sqlite-app](url) It cleared my all doubt. Thanks Again Man
